In [61]:
import pandas as pd
import numpy as np

In [62]:
acceso_internet_tecnologia_provincia = pd.read_csv('Datasets/Acceso a Internet fijo por tecnología y provincia.csv')
acceso_internet_tecnologia_provincia

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2022,1,Buenos Aires,392.045,2.728.865,1.242.121,125.521,66.872,4.555.424
1,2022,1,Capital Federal,102.290,1.217.225,62.308,5.784,29.934,1.417.541
2,2022,1,Catamarca,14.181,15.517,29.118,1.328,2.234,62.378
3,2022,1,Chaco,32.391,64.546,36.662,8.164,2.356,144.119
4,2022,1,Chubut,44.133,66.667,9.184,30.592,21.052,171.628
...,...,...,...,...,...,...,...,...,...
788,2014,1,Santa Fe,322.662,174.296,3.059,5.951,644.000,506.612
789,2014,1,Santiago Del Estero,32.567,3.598,19,915,34.000,37.133
790,2014,1,Tierra Del Fuego,21.618,2.837,648,1,2.934,28.038
791,2014,1,Tucumán,129.717,83,121,13,98.000,130.032
792,*,Los datos provinciales no coinciden a nivel na...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
acceso_internet_tecnologia_provincia.drop(792, inplace=True)
acceso_internet_tecnologia_provincia

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2022,1,Buenos Aires,392.045,2.728.865,1.242.121,125.521,66.872,4.555.424
1,2022,1,Capital Federal,102.290,1.217.225,62.308,5.784,29.934,1.417.541
2,2022,1,Catamarca,14.181,15.517,29.118,1.328,2.234,62.378
3,2022,1,Chaco,32.391,64.546,36.662,8.164,2.356,144.119
4,2022,1,Chubut,44.133,66.667,9.184,30.592,21.052,171.628
...,...,...,...,...,...,...,...,...,...
787,2014,1,Santa Cruz,18.927,100,381,4.092,3.264,26.764
788,2014,1,Santa Fe,322.662,174.296,3.059,5.951,644.000,506.612
789,2014,1,Santiago Del Estero,32.567,3.598,19,915,34.000,37.133
790,2014,1,Tierra Del Fuego,21.618,2.837,648,1,2.934,28.038
791,2014,1,Tucumán,129.717,83,121,13,98.000,130.032

In [64]:
acceso_internet_tecnologia_provincia['Año'].value_counts()

2021      96
2020      96
2018      96
2017      96
2016      96
2015      96
2014      96
2019 *    72
2022      24
2019      24
Name: Año, dtype: int64

In [65]:
acceso_internet_tecnologia_provincia['Año'] = acceso_internet_tecnologia_provincia['Año'].replace('2019 *', '2019')
acceso_internet_tecnologia_provincia['Año'] = acceso_internet_tecnologia_provincia['Año'].replace('*', np.nan)
acceso_internet_tecnologia_provincia['Año'].value_counts()

2021    96
2020    96
2019    96
2018    96
2017    96
2016    96
2015    96
2014    96
2022    24
Name: Año, dtype: int64

In [66]:
acceso_internet_tecnologia_provincia['Trimestre'].value_counts()

1      192
4      192
3      168
2      168
3 *     24
2 *     24
1 *     24
Name: Trimestre, dtype: int64

In [67]:
acceso_internet_tecnologia_provincia['Trimestre'] = acceso_internet_tecnologia_provincia['Trimestre'].replace('3 *', '3')
acceso_internet_tecnologia_provincia['Trimestre'] = acceso_internet_tecnologia_provincia['Trimestre'].replace('2 *', '3')
acceso_internet_tecnologia_provincia['Trimestre'] = acceso_internet_tecnologia_provincia['Trimestre'].replace('1 *', '3')
acceso_internet_tecnologia_provincia['Trimestre'].value_counts()

3    240
1    192
4    192
2    168
Name: Trimestre, dtype: int64

In [68]:
acceso_internet_tecnologia_provincia['Provincia'].value_counts()

Buenos Aires           33
Capital Federal        33
Tierra Del Fuego       33
Santiago Del Estero    33
Santa Fe               33
Santa Cruz             33
San Luis               33
San Juan               33
Salta                  33
Río Negro              33
Neuquén                33
Misiones               33
Mendoza                33
La Rioja               33
La Pampa               33
Jujuy                  33
Formosa                33
Entre Ríos             33
Corrientes             33
Córdoba                33
Chubut                 33
Chaco                  33
Catamarca              33
Tucumán                33
Name: Provincia, dtype: int64

In [69]:
acceso_internet_tecnologia_provincia.dtypes

Año              object
Trimestre        object
Provincia        object
ADSL             object
Cablemodem       object
Fibra óptica     object
Wireless         object
Otros           float64
Total            object
dtype: object

In [70]:
acceso_internet_tecnologia_provincia['ADSL'].value_counts()

22.636     9
48.670     9
11.432     9
12.754     5
40.072     4
          ..
13.037     1
10.663     1
319.396    1
24.556     1
129.717    1
Name: ADSL, Length: 707, dtype: int64

In [71]:
acceso_internet_tecnologia_provincia.sort_values(by=['ADSL'], ascending=False)

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
47,2021,4,Tucumán,97.830,59.022,78.790,2.511,486.000,238.639
271,2019,3,Entre Ríos,97.081,91.081,12.764,17.369,17.529,235.824
228,2019,4,Mendoza,96.678,49.711,24.989,13.672,730.000,185.780
247,2019,3,Entre Ríos,94.947,96.305,12.888,18.530,15.432,238.102
223,2019,4,Entre Ríos,92.981,99.206,12.875,18.561,15.407,239.030
...,...,...,...,...,...,...,...,...,...
288,2019,3,Buenos Aires,1.304.507,2.020.730,336.362,64.867,20.201,3.746.667
432,2017,3,Buenos Aires,1.288.025,1.571.180,124.920,35.058,38.777,3.057.960
264,2019,3,Buenos Aires,1.284.658,2.079.900,382.971,75.240,32.929,3.855.698
240,2019,3,Buenos Aires,1.277.249,2.144.956,425.386,85.572,27.070,3.960.233
408,2017,4,Buenos Aires,1.241.172,1.718.013,131.181,60.082,31.448,3.181.896

In [72]:
acceso_internet_tecnologia_provincia['Cablemodem'].value_counts()

34.984    15
451       14
- 0       14
13.030    13
3.900      7
          ..
49.711     1
69.676     1
60.970     1
37.933     1
83         1
Name: Cablemodem, Length: 681, dtype: int64

In [73]:
acceso_internet_tecnologia_provincia.sort_values(by=['Cablemodem'], ascending=True)

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
539,2016,3,La Rioja,16.891,- 0,15,2,22.000,16.930
635,2015,3,La Rioja,16.725,- 0,16,2,28.000,16.771
755,2014,2,La Rioja,15.864,- 0,14,- 0,34.000,15.912
779,2014,1,La Rioja,15.663,- 0,14,- 0,34.000,15.711
707,2014,4,La Rioja,16.352,- 0,17,- 0,33.000,16.402
...,...,...,...,...,...,...,...,...,...
16,2022,1,Salta,44.714,98.667,40.994,5.950,7.190,197.515
223,2019,4,Entre Ríos,92.981,99.206,12.875,18.561,15.407,239.030
175,2020,2,Entre Ríos,89.391,99.423,13.954,20.042,11.303,234.113
40,2021,4,Salta,46.972,99.808,39.555,5.882,7.188,199.405
484,2017,1,Chubut,43.994,999,916,13.194,4.793,63.896

In [74]:
acceso_internet_tecnologia_provincia['Cablemodem'] = acceso_internet_tecnologia_provincia['Cablemodem'].replace('- 0', '0')
acceso_internet_tecnologia_provincia['Cablemodem'].value_counts()

34.984    15
451       14
0         14
13.030    13
3.900      7
          ..
49.711     1
69.676     1
60.970     1
37.933     1
83         1
Name: Cablemodem, Length: 681, dtype: int64

In [75]:
acceso_internet_tecnologia_provincia.sort_values(by=['Cablemodem'], ascending=True)

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
539,2016,3,La Rioja,16.891,0,15,2,22.000,16.930
635,2015,3,La Rioja,16.725,0,16,2,28.000,16.771
755,2014,2,La Rioja,15.864,0,14,- 0,34.000,15.912
779,2014,1,La Rioja,15.663,0,14,- 0,34.000,15.711
707,2014,4,La Rioja,16.352,0,17,- 0,33.000,16.402
...,...,...,...,...,...,...,...,...,...
16,2022,1,Salta,44.714,98.667,40.994,5.950,7.190,197.515
223,2019,4,Entre Ríos,92.981,99.206,12.875,18.561,15.407,239.030
175,2020,2,Entre Ríos,89.391,99.423,13.954,20.042,11.303,234.113
40,2021,4,Salta,46.972,99.808,39.555,5.882,7.188,199.405
484,2017,1,Chubut,43.994,999,916,13.194,4.793,63.896

In [76]:
acceso_internet_tecnologia_provincia['Fibra óptica']

0      1.242.121
1         62.308
2         29.118
3         36.662
4          9.184
         ...
787          381
788        3.059
789           19
790          648
791          121
Name: Fibra óptica, Length: 792, dtype: object

In [77]:
acceso_internet_tecnologia_provincia.sort_values(by=['Fibra óptica'], ascending=True)

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
238,2019,4,Tierra Del Fuego,13.261,26.821,- 0,- 0,310.000,40.392
227,2019,4,La Rioja,13.738,34.984,- 0,251,29.000,49.002
214,2020,1,Tierra Del Fuego,12.854,25.632,- 0,- 0,308.000,38.794
728,2014,3,Formosa,21.021,4.836,- 0,- 0,80.000,25.937
203,2020,1,La Rioja,13.076,34.984,- 0,251,29.000,48.340
...,...,...,...,...,...,...,...,...,...
259,2019,3,Santa Cruz,10.663,17.056,969,6.544,2.738,37.970
782,2014,1,Neuquén,47.790,28.161,997,10.381,3.051,90.380
758,2014,2,Neuquén,47.767,29.776,997,10.765,2.983,92.288
374,2018,2,Neuquén,46.633,52.855,998,12.649,2.713,115.848
350,2018,3,Neuquén,46.602,54.129,998,12.277,2.712,116.718

In [78]:
acceso_internet_tecnologia_provincia['Fibra óptica'] = acceso_internet_tecnologia_provincia['Fibra óptica'].replace('- 0', '0')
acceso_internet_tecnologia_provincia['Wireless'] = acceso_internet_tecnologia_provincia['Wireless'].replace('- 0', '0')
acceso_internet_tecnologia_provincia.sort_values(by=['Fibra óptica'], ascending=True)

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
238,2019,4,Tierra Del Fuego,13.261,26.821,0,0,310.000,40.392
227,2019,4,La Rioja,13.738,34.984,0,251,29.000,49.002
214,2020,1,Tierra Del Fuego,12.854,25.632,0,0,308.000,38.794
728,2014,3,Formosa,21.021,4.836,0,0,80.000,25.937
203,2020,1,La Rioja,13.076,34.984,0,251,29.000,48.340
...,...,...,...,...,...,...,...,...,...
259,2019,3,Santa Cruz,10.663,17.056,969,6.544,2.738,37.970
782,2014,1,Neuquén,47.790,28.161,997,10.381,3.051,90.380
758,2014,2,Neuquén,47.767,29.776,997,10.765,2.983,92.288
374,2018,2,Neuquén,46.633,52.855,998,12.649,2.713,115.848
350,2018,3,Neuquén,46.602,54.129,998,12.277,2.712,116.718

In [79]:
acceso_internet_tecnologia_provincia.to_csv('test.csv')